networks:
  dev:
    driver: bridge

services: 
  nginx:
    image: nginx:stable-alpine
    container_name: coursework-nginx
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    ports:
      - "80:80"
    depends_on:
      - mongodb
      - backend
      - frontend
    networks:
      - dev

  mongodb:
    image: mongo:6.0
    container_name: coursework-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
    networks:
      - dev
    volumes:
      - mongo-data:/data/db

  backend:
    container_name: coursework-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - dev

  frontend:
    container_name: coursework-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - dev

volumes:
  mongo-data: