networks:
  dev:
    driver: bridge

services: 
  nginx:
    image: nginx:stable-alpine
    container_name: coursework-nginx
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - "80:80"
    depends_on:
      - mongodb
      - backend-1
      - backend-2
      - backend-3
      - frontend
    networks:
      - dev

  mongodb:
    image: mongo:6.0
    container_name: coursework-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
    networks:
      - dev
    volumes:
      - mongo-data:/data/db

  backend-1:
    container_name: coursework-backend-1
    environment:
      - PORT=5000
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/static:/static
    networks:
      - dev

  backend-2:
    container_name: coursework-backend-2
    environment:
      - PORT=5001
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/static:/static
    networks:
      - dev

  backend-3:
    container_name: coursework-backend-3
    environment:
      - PORT=5002
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/static:/static
    networks:
      - dev

  frontend:
    container_name: coursework-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - dev

volumes:
  mongo-data: